# Generated by Django 4.2 on 2023-04-29 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='activate',
            new_name='active',
        ),
    ]
