# Generated by Django 4.2 on 2023-04-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_activate_produit_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='promotions',
            field=models.ManyToManyField(blank=True, related_name='produits', to='product.promotion'),
        ),
    ]
