# Generated by Django 4.2 on 2023-05-03 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_produit_promotions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='promotions',
        ),
        migrations.AddField(
            model_name='produit',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.promotion'),
        ),
    ]
