# Generated by Django 4.2 on 2023-05-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_produit_prix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='promotion',
            new_name='promotions',
        ),
    ]
