# Generated by Django 4.2 on 2023-05-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_produit_prix_remise_alter_produit_prix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix_remise',
            field=models.FloatField(default=0),
        ),
    ]
