# Generated by Django 4.2 on 2023-05-06 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_produit_prix_remise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='prix_remise',
        ),
    ]
